/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CodeGame */

#ifndef _Included_CodeGame
#define _Included_CodeGame
#ifdef __cplusplus
extern "C" {
#endif
#undef CodeGame_EXIT_SUCCESS
#define CodeGame_EXIT_SUCCESS 0L
/*
 * Class:     CodeGame
 * Method:    runGame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CodeGame_runGame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
